import { v4 as uuid } from "uuid";

export const initialProductState = {
  newPrice:"",
  discount:"",
  rating:""
}

export const moreProducts = [
  {
    _id: uuid(),
    name: "Casual Linen Shirt",
    img: "https://picsum.photos/200?1",
    alt: "linen shirt",
    brand: "Allen Solly",
    newPrice: 1899,
    oldPrice: 2499,
    discount: 24,
    size: "M",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: uuid(),
    name: "Slim Fit Denim Shirt",
    img: "https://picsum.photos/200?2",
    alt: "denim shirt",
    brand: "Levis",
    newPrice: 2199,
    oldPrice: 2999,
    discount: 26,
    size: "L",
    idealFor: "M",
    rating: 4.5
  },
  {
    _id: uuid(),
    name: "Checked Cotton Shirt",
    img: "https://picsum.photos/200?3",
    alt: "checked shirt",
    brand: "Peter England",
    newPrice: 1599,
    oldPrice: 1999,
    discount: 20,
    size: "S",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: uuid(),
    name: "Formal White Shirt",
    img: "https://picsum.photos/200?4",
    alt: "white shirt",
    brand: "Van Heusen",
    newPrice: 2099,
    oldPrice: 2799,
    discount: 25,
    size: "XL",
    idealFor: "M",
    rating: 4.6
  },
  {
    _id: uuid(),
    name: "Striped Casual Shirt",
    img: "https://picsum.photos/200?5",
    alt: "striped shirt",
    brand: "Roadster",
    newPrice: 1399,
    oldPrice: 1999,
    discount: 30,
    size: "M",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: uuid(),
    name: "Floral Printed Shirt",
    img: "https://picsum.photos/200?6",
    alt: "floral shirt",
    brand: "H&M",
    newPrice: 1799,
    oldPrice: 2499,
    discount: 28,
    size: "L",
    idealFor: "M",
    rating: 4.2
  },
  {
    _id: uuid(),
    name: "Solid Black Shirt",
    img: "https://picsum.photos/200?7",
    alt: "black shirt",
    brand: "Zara",
    newPrice: 2299,
    oldPrice: 2999,
    discount: 23,
    size: "M",
    idealFor: "M",
    rating: 4.4
  },
  {
    _id: uuid(),
    name: "Chambray Shirt",
    img: "https://picsum.photos/200?8",
    alt: "chambray shirt",
    brand: "Levis",
    newPrice: 1999,
    oldPrice: 2699,
    discount: 26,
    size: "L",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: uuid(),
    name: "Printed Beach Shirt",
    img: "https://picsum.photos/200?9",
    alt: "beach shirt",
    brand: "HRX",
    newPrice: 1499,
    oldPrice: 1999,
    discount: 25,
    size: "S",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: uuid(),
    name: "Oxford Blue Shirt",
    img: "https://picsum.photos/200?10",
    alt: "oxford shirt",
    brand: "UCB",
    newPrice: 1899,
    oldPrice: 2499,
    discount: 24,
    size: "XL",
    idealFor: "M",
    rating: 4.5
  },
  {
    _id: uuid(),
    name: "Half Sleeve Casual Shirt",
    img: "https://picsum.photos/200?11",
    alt: "half sleeve shirt",
    brand: "Roadster",
    newPrice: 1299,
    oldPrice: 1799,
    discount: 28,
    size: "M",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: uuid(),
    name: "Printed Party Shirt",
    img: "https://picsum.photos/200?12",
    alt: "party shirt",
    brand: "H&M",
    newPrice: 1999,
    oldPrice: 2599,
    discount: 23,
    size: "L",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: uuid(),
    name: "Classic Grey Shirt",
    img: "https://picsum.photos/200?13",
    alt: "grey shirt",
    brand: "Allen Solly",
    newPrice: 1799,
    oldPrice: 2399,
    discount: 25,
    size: "M",
    idealFor: "M",
    rating: 4.2
  },
  {
    _id: uuid(),
    name: "Checked Flannel Shirt",
    img: "https://picsum.photos/200?14",
    alt: "flannel shirt",
    brand: "Levis",
    newPrice: 2499,
    oldPrice: 3299,
    discount: 24,
    size: "L",
    idealFor: "M",
    rating: 4.6
  },
  {
    _id: uuid(),
    name: "Slim Fit Formal Shirt",
    img: "https://picsum.photos/200?15",
    alt: "formal shirt",
    brand: "Van Heusen",
    newPrice: 2199,
    oldPrice: 2899,
    discount: 24,
    size: "XL",
    idealFor: "M",
    rating: 4.5
  },
  {
    _id: uuid(),
    name: "Casual Printed Shirt",
    img: "https://picsum.photos/200?16",
    alt: "printed shirt",
    brand: "Roadster",
    newPrice: 1399,
    oldPrice: 1999,
    discount: 30,
    size: "S",
    idealFor: "M",
    rating: 4.1
  },
  {
    _id: uuid(),
    name: "Solid Navy Shirt",
    img: "https://picsum.photos/200?17",
    alt: "navy shirt",
    brand: "Zara",
    newPrice: 2299,
    oldPrice: 2999,
    discount: 23,
    size: "M",
    idealFor: "M",
    rating: 4.4
  },
  {
    _id: uuid(),
    name: "Casual Summer Shirt",
    img: "https://picsum.photos/200?18",
    alt: "summer shirt",
    brand: "HRX",
    newPrice: 1299,
    oldPrice: 1799,
    discount: 28,
    size: "L",
    idealFor: "M",
    rating: 4.0
  },
  {
    _id: uuid(),
    name: "Premium Cotton Shirt",
    img: "https://picsum.photos/200?19",
    alt: "cotton shirt",
    brand: "UCB",
    newPrice: 1999,
    oldPrice: 2599,
    discount: 23,
    size: "XL",
    idealFor: "M",
    rating: 4.3
  },
  {
    _id: uuid(),
    name: "Casual Check Shirt",
    img: "https://picsum.photos/200?20",
    alt: "check shirt",
    brand: "Peter England",
    newPrice: 1599,
    oldPrice: 2199,
    discount: 27,
    size: "M",
    idealFor: "M",
    rating: 4.2
  }
];